### ISSUE TITLE
 Is it possible to create multiple tasks at once?

### ISSUE THREAD

**Issue by Ektorr** [andrzejkupczyk/mantis-todolists#16]
Hi!,
This plugin seems great to me, thank you very much! I wanted to ask you if you could do something to create several tasks at once. For example, entering texts separated by ";" or CR in the input box

**Comment by andrzejkupczyk** [comment]
Hey @Ektorr, it's a good and fairly easy to implement idea :massage_man:

**Comment by Ektorr** [comment]
Thank you very much, this will help me a lot!

**Comment by andrzejkupczyk** [comment]
@Ektorr , a new version of the plugin has been released. It is now possible to create multiple tasks at once.  
More details can be found in the linked pull request.

This new functionality may need further enhancements, but it should be sufficient for now.
