### ISSUE TITLE
Getting error 405

### ISSUE THREAD

**Issue by sintaq83** [andrzejkupczyk/mantis-todolists#26]
Hi,
Am getting error 405 when trying to EDIT or DELETE a task

![image](https://user-images.githubusercontent.com/79757612/133463688-9d144f9a-b2ec-4fed-af04-b2e8dea30779.png)

**Comment by andrzejkupczyk** [comment]
Thanks, @sintaq83 . This looks like a problem with your environment. I'll investigate this as soon as possible.

**Comment by andrzejkupczyk** [comment]
@sintaq83 , what is your server configuration? Does it accept PUT and DELETE requests?

https://gridpane.com/kb/making-nginx-accept-put-delete-and-patch-verbs/
