### ISSUE TITLE
Can't delete tasks and edit task. Only create

### ISSUE THREAD

**Issue by VadimVadimych** [andrzejkupczyk/mantis-todolists#29]
**Describe the bug**
I can't delete tasks.
When editing, they are not edited, but a new one is created
Language is Russian

**To Reproduce**
1. Go to 'View Issue/View Issue Details/Things to do'
2. Write name of task, Click on 'Add'
3. Click on 'Remove'
4. Nothing happens
5. Click 'Edit task'
6. After edit, the old one remains and a new one is created with the edited name

**Expected behavior**
I assumed that editing only changes the name

**Screenshots**
screenshots below

**Environment (please complete the following information):**
 - MantisBT version: 2.24.4
 - Plugin version: 2.4.0
 - Database: MySQL 5.7.27
 - PHP 5.7.27
 - Chrome browser 97.0.4692.71
 
**Additional context**
![1](https://user-images.githubusercontent.com/97958589/149940385-0da6ba47-6b88-43b7-b898-0338a2ef3861.jpg)
![2](https://user-images.githubusercontent.com/97958589/149940410-05039e52-7e8a-4174-8700-f927a6c1c1ad.jpg)
![3](https://user-images.githubusercontent.com/97958589/149940420-754cc388-47aa-4025-92aa-5520d521f006.jpg)
![4](https://user-images.githubusercontent.com/97958589/149940432-6f0f1933-30ef-42d2-9581-4c50dc08944b.jpg)
![5](https://user-images.githubusercontent.com/97958589/149940444-8a549f26-69b1-4f47-ba34-5871ae47cf68.jpg)

**Comment by andrzejkupczyk** [comment]
@VadimVadimych thank you very much for the detailed information you have given!

Unfortunately I was not able to reproduce this bug. Would you mind repeat the steps mentioned above with the dev console opened? Maybe we could find a clue within "console" or "network" tab.

**Comment by VadimVadimych** [comment]
Maybe we can find a clue in the "console" or "network" tab. Thanks in advance.

output in the console at the moment of deletion:
[new.kof-palitra.ru-1642514711660.log](https://github.com/andrzejkupczyk/mantis-todolists/files/7889629/new.kof-palitra.ru-1642514711660.log)

and from 'network':

![6](https://user-images.githubusercontent.com/97958589/149953095-66a204c2-ec25-4654-910a-a290d1f6fe9e.jpg)

**Comment by andrzejkupczyk** [comment]
This is weird 🤔 I will try to find the cause and fix the problem as soon as possible, but in the meantime could you please show me contents of the "Payload" tab as well?

**Comment by VadimVadimych** [comment]
I don't understand it myself.
![7](https://user-images.githubusercontent.com/97958589/150013670-a0c7fdb3-77b9-40bd-9cc1-d75e2111e9c6.jpg)

**Comment by andrzejkupczyk** [comment]
Thank you very much. At least now we know that it is related to front-end.

**Comment by VadimVadimych** [comment]
I translated strings into Russian, in case someone might need it
[strings_russian.txt](https://github.com/andrzejkupczyk/mantis-todolists/files/7896973/strings_russian.txt)

**Comment by andrzejkupczyk** [comment]
Hey @VadimVadimych 👋🏻 Once again thanks for reporting this issue and all your help.
I've just created a new release [v2.5.0](https://github.com/andrzejkupczyk/mantis-todolists/releases/tag/v2.5.0). It contains changes which I hope fixes this problem. The Russian language is included as well 😉 

Please verify if this fixes the bug because I was not able to reproduce it.

**Comment by VadimVadimych** [comment]
Hello Andrzej!
Thank you so much for your time on this problem!
Everything is working perfectly!
Thank you again.
