### ISSUE TITLE
Missing german language support

### ISSUE THREAD

**Issue by Firehunter23** [andrzejkupczyk/mantis-todolists#34]
Hi!

I jsut installed your plugin in mantis using the latest version.
As of our users are german I quickly translated your file.

See attached file if you want to implement.

Greetings!

[strings_german.txt](https://github.com/andrzejkupczyk/mantis-todolists/files/9040540/strings_german.txt)

**Comment by andrzejkupczyk** [comment]
Thanks, @Firehunter23 !
